# Generated by Django 3.1 on 2020-08-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='package',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='message',
            field=models.TextField(db_index=True, max_length=500, null=True),
        ),
    ]
